spring:
  flyway:
    locations: "classpath:/db/migration,classpath:/local/db/migration"
  datasource:
    hikari:
      connection-test-query: SELECT 1L
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: db_fiscal-database-pool
      auto-commit: false
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
    url: "${DB_URL:jdbc:postgresql://localhost:5432/postgres?ssl=false}"
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:postgres}"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: false
        ddl-auto: none