spring:
  flyway:
    locations: "classpath:/db/migration,classpath:/local/db/migration"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password: postgresql
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        generate_statistics: false
        ddl-auto: none